# 1.7.1 Gym

安装gym

In [1]:
pip install gym

Note: you may need to restart the kernel to use updated packages.


智能体得到某个观测后，它就会输出一个动作。这个动作会被环境拿去执行某个步骤，然后环境就会往前走一步，返回新的观测、奖励以及一个 flag 变量 done，done 决定这个游戏是不是结束了。伪代码实现强化学习框架如下：

import gym
env = gym.make("Taxi-v3")
observation = env.reset()
agent = load_agent()
for step in range(100):
action = agent(observation)
observation, reward, done, info = env.step(action)

当我们执行这段代码时，机器人会驾驶着小车朝某个方向一直跑，直到我们看不见，这是因为我们还没开始训练机器人。

In [8]:
import gym # 导入 Gym 的 Python 接口环境包
env = gym.make('CartPole-v0') # 构建实验环境
env.action_space.sample()
env.reset() # 重置一个回合
for _ in range(1000):
    env.render() # 显示图形界面
    action = env.action_space.sample() # 从动作空间中随机选取一个动作
    env.step(action) # 用于提交动作，括号内是具体的动作
env.close() # 关闭环境

Gym 库中的大部分小游戏都可以用一个普通的实数或者向量来表示动作。输出 env.action_space.sample()的返回值，能看到输出为 1 或者 0。env.action_space.sample() 的含义是，在该游戏的所有动作空间里随机选择一个作为输出。在这个例子中，动作只有两个：0 和 1，一左一右。env.step() 方法有 4 个返回值：observation状态信息、reward奖励值、done是否已经完成、info 用于诊断和调试的信息。

在每个训练中都要使用的返回值有 observation、reward、done。但 observation 的结构会由于游戏的不同而发生变化。以 CartPole-v0 为例，我们对代码进行修改：，从输出可以看出这是一个四维的观测。在其他游戏中会有维度更多的情况出现。

In [9]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    print(observation)
env.close()

[-0.0225657  -0.19272539  0.02717709  0.27520633]
[-0.02642021 -0.38822433  0.03268122  0.57633555]
[-0.0341847  -0.58378875  0.04420793  0.87913215]
[-0.04586047 -0.38929448  0.06179057  0.6006686 ]
[-0.05364636 -0.5852239   0.07380395  0.9121568 ]
[-0.06535085 -0.78126264  0.09204708  1.2270931 ]
[-0.0809761  -0.97744095  0.11658894  1.5471385 ]
[-0.10052492 -1.1737539   0.14753172  1.8738081 ]
[-0.12399999 -0.9805191   0.18500787  1.630322  ]
[-0.14361037 -0.78799     0.21761431  1.4005392 ]
[-0.15937017 -0.98504996  0.2456251   1.7526325 ]
[-0.17907117 -0.7934111   0.28067774  1.5452919 ]
[-0.19493939 -0.60253274  0.31158358  1.3516186 ]
[-0.20699005 -0.4123571   0.33861595  1.1702213 ]
[-0.21523719 -0.22281514  0.36202037  0.99971455]
[-0.2196935  -0.4205272   0.38201466  1.3811843 ]
[-0.22810404 -0.23159361  0.40963838  1.2278132 ]
[-0.23273592 -0.42907697  0.43419462  1.6166236 ]
[-0.24131745 -0.62604904  0.4665271   2.0083458 ]
[-0.25383842 -0.43770644  0.506694    1.88826   ]


[-5.1351175 -3.4628153 18.096256   6.159433 ]
[-5.204374  -3.6690395 18.219444   6.1839633]
[-5.277755  -3.4935322 18.343124   5.798023 ]
[-5.3476253 -3.3113716 18.459084   5.4164715]
[-5.4138527 -3.1240816 18.567413   5.044779 ]
[-5.4763346 -3.3211634 18.668308   5.2468596]
[-5.542758  -3.5181158 18.773247   5.484453 ]
[-5.61312   -3.7143013 18.882935   5.755462 ]
[-5.687406  -3.5185952 18.998045   5.471878 ]
[-5.757778  -3.7111855 19.107483   5.8010798]
[-5.8320017 -3.5121734 19.223503   5.587429 ]
[-5.902245 -3.69922  19.335253  5.956005]
[-5.9762297 -3.4970856 19.454372   5.825115 ]
[-6.046171  -3.6758628 19.570875   6.212882 ]
[-6.1196885 -3.4695668 19.695133   6.1746597]
[-6.1890798 -3.262224  19.818626   6.1883802]
[-6.2543244 -3.0533793 19.942392   6.253412 ]
[-6.315392  -3.2113683 20.067461   6.6234694]
[-6.379619  -2.9946952 20.19993    6.787025 ]
[-6.439513  -3.1389718 20.33567    7.121229 ]
[-6.5022926 -3.2760465 20.478096   7.431566 ]
[-6.5678134 -3.4070008 20.626728   7.7

[-16.82252    -3.0510707  46.585094   11.057535 ]
[-16.883541  -2.79339   46.806244  11.54015 ]
[-16.93941    -2.5551333  47.03705    11.971481 ]
[-16.99051    -2.7367887  47.276478   11.725525 ]
[-17.045246   -2.9540856  47.510986   11.35868  ]
[-17.104328   -2.8129659  47.73816    11.443711 ]
[-17.160587   -2.7009597  47.967033   11.411557 ]
[-17.214607   -2.6114829  48.195267   11.281285 ]
[-17.266836   -2.5356636  48.42089    11.077661 ]
[-17.31755    -2.8298302  48.642445   10.675303 ]
[-17.374147  -2.752155  48.85595   10.387789]
[-17.42919    -2.6648893  49.063705   10.076586 ]
[-17.482487   -2.9306622  49.26524     9.946175 ]
[-17.541101   -2.8161807  49.46416     9.605996 ]
[-17.597424   -3.0596085  49.65628     9.648874 ]
[-17.658617   -2.9132373  49.84926     9.300584 ]
[-17.71688   -3.134529  50.03527    9.485314]
[-17.779572   -3.3456898  50.224976    9.726613 ]
[-17.846485   -3.153748   50.41951     9.4270315]
[-17.909561   -2.9478533  50.60805     9.166951 ]
[-17.968517 

[-24.736378    -0.81205213  84.247314    13.281533  ]
[-24.752619    -0.90491897  84.51294     13.324744  ]
[-24.770718   -1.0420878  84.779434   13.218506 ]
[-24.79156   -0.838946  85.04381   13.535734]
[-24.808338    -0.68657196  85.31452     13.694355  ]
[-24.82207   -0.969403  85.58841   13.181574]
[-24.841457    -0.90128446  85.85204     13.051562  ]
[-24.859482   -0.8572547  86.11307    12.833717 ]
[-24.876627   -1.1882324  86.36974    12.413678 ]
[-24.900393   -1.1467838  86.61802    12.121259 ]
[-24.923328   -1.4569751  86.86044    11.938073 ]
[-24.952467   -1.7532213  87.099205   11.875426 ]
[-24.987532   -2.0341017  87.336716   11.924751 ]
[-25.028214   -2.2972565  87.57521    12.071493 ]
[-25.07416    -2.1525924  87.81664    11.759133 ]
[-25.11721    -2.3651724  88.05182    12.031178 ]
[-25.164515   -2.5491343  88.29244    12.331685 ]
[-25.215498  -2.699712  88.53908   12.640192]
[-25.269491   -2.8141983  88.791885   12.944115 ]
[-25.325775   -2.8930156  89.050766   13.24055

[-35.125385   -3.4754524 132.097      12.391606 ]
[-35.194893   -3.6500072 132.34483    12.694459 ]
[-35.267895   -3.7878137 132.59871    12.998946 ]
[-35.34365    -3.8871715 132.85869    13.295778 ]
[-35.421394   -3.5768328 133.1246     13.243177 ]
[-35.49293    -3.2491872 133.38948    13.326506 ]
[-35.557915   -2.9085586 133.656      13.552762 ]
[-35.616085   -2.5590777 133.92706    13.916231 ]
[-35.667267  -2.207069 134.20538   14.396105]
[-35.711407   -2.2375865 134.4933     14.594225 ]
[-35.75616   -2.30793  134.78519   14.671686]
[-35.80232    -2.4354098 135.07863    14.577002 ]
[-35.85103   -2.628345 135.37016   14.290512]
[-35.903595   -2.8812485 135.65598    13.844384 ]
[-35.96122    -2.7949626 135.93286    13.795495 ]
[-36.017117   -2.7476962 136.20877    13.622805 ]
[-36.07207    -2.7226696 136.48123    13.374484 ]
[-36.126526   -3.0675995 136.74872    12.993495 ]
[-36.187878   -3.0374453 137.00859    12.69663  ]
[-36.248627   -3.3552032 137.26251    12.583511 ]
[-36.31573  

[-46.456665   -2.0912805 177.06595    11.369798 ]
[-46.49849    -1.8044797 177.29333    11.45562  ]
[-46.53458    -1.8724134 177.52246    11.764273 ]
[-46.572025   -1.9281486 177.75774    12.05632  ]
[-46.61059    -1.9791232 177.99887    12.321116 ]
[-46.650173  -2.035011 178.24529   12.539175]
[-46.690872   -1.7319876 178.49608    13.063494 ]
[-46.725513   -1.8279866 178.75734    13.102444 ]
[-46.762074   -1.9662983 179.0194     12.995734 ]
[-46.8014     -1.7620163 179.27931    13.316855 ]
[-46.83664    -1.6061044 179.54564    13.484794 ]
[-46.86876    -1.8839206 179.81534    12.979756 ]
[-46.90644    -1.8098166 180.07494    12.862271 ]
[-46.942635   -2.1308873 180.33218    12.355693 ]
[-46.985252   -2.4507983 180.5793     11.929541 ]
[-47.034267   -2.7626545 180.81789    11.606994 ]
[-47.089523   -2.6989715 181.05002    11.3007965]
[-47.1435     -2.9855487 181.27605    11.201717 ]
[-47.203213   -2.8868587 181.50008    10.877186 ]
[-47.26095    -3.1423419 181.71762    10.975081 ]
[-47

要查看当前 Gym 库已经注册了哪些环境，可以使用以下代码

In [10]:
from gym import envs
env_specs = envs.registry.all()
envs_ids = [env_spec.id for env_spec in env_specs]
print(envs_ids)

['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v1', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'Reacher-v2', 'Pusher-v2', 'InvertedPendulum-v2', 'InvertedDoublePendulum-v2', 'HalfCheetah-v2', 'HalfCheetah-v3', 'Hopper-v2', 'Hopper-v3', 'Swimmer-v2', 'Swimmer-v3', 'Walker2d-v2', 'Walker2d-v3', 'Ant-v2', 'Ant-v3', 'Humanoid-v2', 'Humanoid-v3', 'HumanoidStandup-v2']


    每个环境都定义了自己的观测空间和动作空间。环境 env 的观测空间用 env.observation_space 表示，动作空间用 env.action_space 表示。观测空间和动作空间既可以是离散空间（取值是有限个离散的值），也可以是连续空间（取值是连续的值）。在 Gym 库中，一般离散空间用 gym.spaces.Discrete 类表示，连续空间用 gym.spaces.Box 类表示。
    例如，环境 MountainCar-v0 的观测空间是 Box(2,)，表示观测可以用 2 个 float 值表示；环境 MountainCar-v0 的动作空间是 Discrete(3)，表示动作取值自 0,1,2。对于离散空间，Discrete 类实例的成员 n 表示有几个可能的取值；对于连续空间，Box 类实例的成员 low 和 high 表示每个浮点数的取值范围。

# 1.7.2 MountainCar-v0 例子

接下来，我们通过一个例子来学习如何与 Gym 库进行交互。我们选取小车上山（MountainCar-v0）作为例子。
首先我们来看看这个任务的观测空间和动作空间：

In [22]:
import gym
env = gym.make('MountainCar-v0')
print('观测空间 = {}'. format(env.observation_space))
print('动作空间 = {}'. format(env.action_space))
print('观测范围 = {} ~ {}'. format(env.observation_space.low,
env.observation_space.high))
print('动作数 = {}'. format(env.action_space.n))

观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测范围 = [-1.2  -0.07] ~ [0.6  0.07]
动作数 = 3


由输出可知，观测空间是形状为 (2,) 的浮点型 np.array，动作空间是取 0,1,2 的 int 型数值。
接下来考虑智能体。智能体往往是我们自己实现的。我们可以实现一个智能体类——BespokeAgent类，代码如下：

In [24]:
class BespokeAgent:
    def __init__(self, env):
        pass
    def decide(self, observation): # 决策
        position, velocity = observation#位置与速度
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03,0.3 * (position + 0.9) ** 4 - 0.008)
        ub = -0.07 * (position + 0.38) ** 2 + 0.07
        if lb < velocity < ub:
            action = 2
        else:
            action = 0
        return action # 返回动作
    def learn(self, *args): # 学习
        pass
    
agent = BespokeAgent(env)

智能体的 decide() 方法实现了决策功能，而 learn() 方法实现了学习功能。BespokeAgent 类是一个比较简单的类，它只能根据给定的数学表达式进行决策，不能有效学习，所以它并不是一个真正意义上的强化学习智能体类。但是，它用于演示智能体和环境的交互已经足够了。
接下来我们试图让智能体与环境交互，代码如下。

In [25]:
def play_montecarlo(env, agent, render=False, train=False):
    episode_reward = 0. # 记录回合总奖励，初始化为0
    observation = env.reset() # 重置游戏环境，开始新回合
    while True: # 不断循环，直到回合结束
        if render: # 判断是否显示
            env.render() # 显示图形界面，图形界面可以用 env.close() 语句关闭
        action = agent.decide(observation)
        next_observation, reward, done, _ = env.step(action) # 执行动作
        episode_reward += reward # 收集回合奖励
        if train: # 判断是否训练智能体
            agent.learn(observation, action, reward, done) # 学习
        if done: # 回合结束，跳出循环
            break
        observation = next_observation
    return episode_reward # 返回回合总奖励

上面代码中的 play_montecarlo() 函数可以让智能体和环境交互一个回合，这个函数有 4 个参数。 env是环境类。agent 是智能体类。render 是 bool 型变量，指示在运行过程中是否要图形化显示，如果函数参数 render 为 True，那么在交互过程中会调用 env.render() 以显示图形界面，而这个界面可以通过调用env.close() 关闭。train 是 bool 型的变量，指示在运行过程中是否训练智能体，在训练过程中应当设置为True，以调用 agent.learn() 函数；在测试过程中应当设置为 False，使得智能体不变。这个函数有一个返回值 episode_reward，是 float 型的数值，表示智能体与环境交互一个回合的回合总奖励。
接下来，我们使用下面的代码让智能体和环境交互一个回合，并在交互过程中进行图形化显示，可用env.close() 语句关闭图形界面。

In [26]:
env.seed(0) # 设置随机数种子,只是为了让结果可以精确复现,一般情况下可删去
episode_reward = play_montecarlo(env, agent, render=True)
print('回合奖励 = {}'. format(episode_reward))
env.close() # 此语句可关闭图形界面

回合奖励 = -123.0


为了系统评估智能体的性能，下列代码求出了连续交互 100 回合的平均回合奖励。

In [29]:
import numpy as np
episode_rewards = [play_montecarlo(env, agent) for _ in range(100)]
print('平均回合奖励 = {}'. format(np.mean(episode_rewards)))

平均回合奖励 = -101.75


小车上山环境有一个参考的回合奖励值 −110，如果连续 100 个回合的平均回合奖励大于 −110，则认为这个任务被解决了。BespokeAgent 类对应的策略的平均回合奖励就在 −110 左右。
测试智能体在 Gym 库中某个任务的性能时，学术界一般最关心 100 个回合的平均回合奖励。至于为什么是 100 个回合而不是其他回合数（比如 128 个回合），完全是习惯使然，没有什么特别的原因 [3] 。对于有些任务，还会指定一个参考的回合奖励值，当连续 100 个回合的奖励大于指定的值时，就认为这个任务被解决了。但是，并不是所有的任务都指定了这样的值。对于没有指定值的任务，就无所谓任务被解决了或者没有被解决。

以下是gym官网的示例代码
采取随机运动模型

In [32]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(500):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

引入时间步

In [33]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[-0.01020485 -0.00611509  0.03951677 -0.04747547]
[-0.01032715 -0.20178075  0.03856726  0.2574088 ]
[-0.01436276 -0.00723003  0.04371544 -0.02286431]
[-0.01450736  0.18723862  0.04325815 -0.30144036]
[-0.01076259 -0.00847233  0.03722934  0.00456537]
[-0.01093204 -0.20410788  0.03732065  0.30875826]
[-0.0150142  -0.39974117  0.04349582  0.6129736 ]
[-0.02300902 -0.5954431   0.05575529  0.9190326 ]
[-0.03491788 -0.7912726   0.07413594  1.228704  ]
[-0.05074333 -0.5971788   0.09871002  0.9601389 ]
[-0.06268691 -0.4035123   0.1179128   0.7000269 ]
[-0.07075716 -0.21020527  0.13191333  0.44666588]
[-0.07496126 -0.01717203  0.14084665  0.19830176]
[-0.0753047  -0.21399812  0.14481269  0.53188944]
[-0.07958467 -0.41082823  0.15545048  0.8664705 ]
[-0.08780123 -0.60768515  0.17277989  1.2037139 ]
[-0.09995493 -0.41516542  0.19685416  0.969779  ]
Episode finished after 17 timesteps
[ 0.02742475 -0.04306896 -0.0328306  -0.04352677]
[ 0.02656337 -0.23770513 -0.03370113  0.23861969]
[ 0.02180926 -

[0.02835306 0.0256166  0.01118821 0.02720521]
[ 0.02886539  0.22057633  0.01173231 -0.26192683]
[ 0.03327692  0.41552886  0.00649377 -0.5508863 ]
[ 0.0415875   0.610559   -0.00452395 -0.84151614]
[ 0.05379868  0.80574244 -0.02135427 -1.1356183 ]
[ 0.06991352  0.61090624 -0.04406664 -0.8497084 ]
[ 0.08213165  0.41641206 -0.06106081 -0.5712017 ]
[ 0.09045989  0.6123347  -0.07248484 -0.8824788 ]
[ 0.10270659  0.8083623  -0.09013442 -1.19704   ]
[ 0.11887383  1.0045278  -0.11407521 -1.5165573 ]
[ 0.13896438  0.8109558  -0.14440636 -1.261552  ]
[ 0.15518351  0.61794525 -0.1696374  -1.0173576 ]
[ 0.16754241  0.81487244 -0.18998456 -1.3581429 ]
Episode finished after 17 timesteps
[0.03401461 0.02071938 0.02786748 0.00942661]
[ 0.034429   -0.17479092  0.02805601  0.31077015]
[ 0.03093318 -0.37030113  0.03427141  0.6121674 ]
[ 0.02352716 -0.5658849   0.04651476  0.9154446 ]
[ 0.01220946 -0.76160395  0.06482365  1.2223761 ]
[-0.00302262 -0.5673743   0.08927117  0.9506883 ]
[-0.0143701  -0.373559

[ 0.03778131 -0.3870769   0.00624008  0.65029365]
[ 0.03003977 -0.19204244  0.01924596  0.3595822 ]
[0.02619892 0.00280071 0.0264376  0.07302956]
[ 0.02625494  0.19753386  0.02789819 -0.21119635]
[0.03020561 0.00202436 0.02367426 0.09015478]
[ 0.0302461  -0.19342878  0.02547736  0.39021194]
[0.02637753 0.00132248 0.0332816  0.10566937]
[ 0.02640398 -0.19426022  0.03539499  0.40866393]
[0.02251877 0.00034247 0.04356826 0.12734668]
[ 0.02252562 -0.19537567  0.0461152   0.4334503 ]
[ 0.01861811 -0.39111915  0.0547842   0.74030644]
[ 0.01079572 -0.586953    0.06959033  1.049715  ]
[-9.4333466e-04 -7.8292567e-01  9.0584636e-02  1.3634056e+00]
[-0.01660185 -0.58904773  0.11785274  1.1003765 ]
[-0.0283828  -0.78550667  0.13986027  1.4275893 ]
[-0.04409293 -0.5923619   0.16841206  1.1816862 ]
[-0.05594017 -0.7892207   0.19204578  1.522076  ]
Episode finished after 41 timesteps
[-0.04002633 -0.00669946  0.00592057 -0.01835895]
[-0.04016031  0.18833709  0.00555339 -0.309168  ]
[-0.03639357  0.38